foreground            #e5e2e1
background            #131313
selection_foreground  #2c3132
selection_background  #c3c7c8
url_color             #d3c3be
cursor                #c3c7c8
cursor_text_color     #2c3132

color0   #131313
color1   #ffb4ab
color2   #c3c7c8
color3   #d3c3be
color4   #c3c7c8
color5   #d3c3be
color6   #29201d
color7   #e5e2e1

color8   #8d9192
color9   #ffb4ab
color10  #c3c7c8
color11  #d3c3be
color12  #c3c7c8
color13  #d3c3be
color14  #29201d
color15  #e5e2e1

tab_bar_background              #131313
tab_bar_margin_color            #131313
active_tab_foreground           #2c3132
active_tab_background           #c3c7c8
inactive_tab_foreground         #c3c7c8
inactive_tab_background         #131313
