foreground            #e5e1e5
background            #131316
selection_foreground  #2d2c54
selection_background  #c4c2f3
url_color             #d7c782
cursor                #c4c2f3
cursor_text_color     #2d2c54

color0   #131316
color1   #ffb4ab
color2   #c4c2f3
color3   #d7c782
color4   #c4c2f3
color5   #d7c782
color6   #baab69
color7   #e5e1e5

color8   #928f99
color9   #ffb4ab
color10  #c4c2f3
color11  #d7c782
color12  #c4c2f3
color13  #d7c782
color14  #baab69
color15  #e5e1e5

tab_bar_background              #131316
tab_bar_margin_color            #131316
active_tab_foreground           #2d2c54
active_tab_background           #c4c2f3
inactive_tab_foreground         #c8c5cf
inactive_tab_background         #131316
