foreground            #e6e1e9
background            #141318
selection_foreground  #331c7c
selection_background  #cbbeff
url_color             #ffb68f
cursor                #cbbeff
cursor_text_color     #331c7c

color0   #141318
color1   #ffb4ab
color2   #cbbeff
color3   #ffb68f
color4   #cbbeff
color5   #ffb68f
color6   #532100
color7   #e6e1e9

color8   #938e9d
color9   #ffb4ab
color10  #cbbeff
color11  #ffb68f
color12  #cbbeff
color13  #ffb68f
color14  #532100
color15  #e6e1e9

tab_bar_background              #141318
tab_bar_margin_color            #141318
active_tab_foreground           #331c7c
active_tab_background           #cbbeff
inactive_tab_foreground         #cac4d3
inactive_tab_background         #141318
